twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        app_games_images_directory: '%env(GAME_IMAGES_DIRECTORY)%'

when@test:
    twig:
        strict_variables: true
