  add-assert[m
  crud_user[m
  front-css-global[m
* [32mmaster[m
  registration-form[m
  style-login-navbar[m
  [31mremotes/origin/Back-GameController[m
  [31mremotes/origin/Backoffice-Game-Templates[m
  [31mremotes/origin/Fix-name-link[m
  [31mremotes/origin/GameController[m
  [31mremotes/origin/GameType[m
  [31mremotes/origin/HEAD[m -> origin/master
  [31mremotes/origin/Home-twig[m
  [31mremotes/origin/MainController[m
  [31mremotes/origin/MySlugger[m
  [31mremotes/origin/SP0-base-docs[m
  [31mremotes/origin/Update-home[m
  [31mremotes/origin/add-assert[m
  [31mremotes/origin/authentification[m
  [31mremotes/origin/crud-checkpoint[m
  [31mremotes/origin/crud_user[m
  [31mremotes/origin/fix-fixtures[m
  [31mremotes/origin/fix-home-page[m
  [31mremotes/origin/fixtures[m
  [31mremotes/origin/front-css-global[m
  [31mremotes/origin/instance-CRUD[m
  [31mremotes/origin/instance-tpl-css[m
  [31mremotes/origin/master[m
  [31mremotes/origin/registration-form[m
  [31mremotes/origin/scanQR[m
  [31mremotes/origin/scanQR-POST[m
  [31mremotes/origin/style-login-navbar[m
